version: '3.1'
services:
    mysql:
        restart: always
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - databasevolume:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
    openemr:
        restart: always
        build:
            context: dockerfiles/prod
            args:
                - TELEHEALTH_BASE_URL=${TELEHEALTH_BASE_URL}
                - TELEHEALTH_PORT=${TELEHEALTH_PORT}
                - TELEHEALTH_API_TOKEN=${TELEHEALTH_API_TOKEN}
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}

        ports:
            - ${OPENEMR_PORT}:80
        volumes:
            - logvolume01:/var/log
            - sitevolume:/var/www/html/sites
        depends_on:
            - mysql
volumes:
    logvolume01: {}
    sitevolume: {}
    databasevolume: {}
